name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: install & build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: deploy
        env:
          access_token: ${{ secrets.CI_TOKEN }}
        run: |
          echo $access_token
          sed -i 's/\r//' deploy.sh
          bash ./deploy.sh
