name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install & build
        run: |
          npm install pnpm@7 -g
          pnpm install
          npm run build

      - name: deploy
        env:
          access_token: ${{ secrets.CI_TOKEN }}
        run: |
          echo $access_token
          sed -i 's/\r//' deploy.sh
          bash ./deploy.sh
